# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Home
    title: Homepage
    link: homepage
    class: homepage
  - label: About
    link: page/2
    submenu:
        - label: Sobre el Festival
          link: entry/39
        - label: Convocatoria
          class: menu-item-class
          link: entry/convocatoria-al-28-festival-de-poesia-de-la-habana
        - label: Programa del Mitin Poético Virtual
          link: entry/114
        - link: entry/41 # These two have no `label`, so they will show up as the title
        - class: sub-class
          link: page/42
  - label: All pages
    link: pages/
  - label: Cubapoesia
    link: http://www.cubapoesia.cult.cu
    class: bolt-site
    title: Visit the Cubapoesia website!

foo: bar
